import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // home,
  shops,
  categories,
}: Readonly<{
  children: React.ReactNode;
  home: React.ReactNode;
  shops: React.ReactNode;
  categories: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">
            {children}
            {categories}
            {shops}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
